## secrets.yaml example

ota_password: "***"

fallback_ap_passwd: "***"
api_password: "***"
api_encryption_key: "***"

wifi_ssid: "WIFI_SSID"
wifi_password: "***"

domain: ".secretnetwork.private"
timezone: "Europe/Dublin"

mqtt_password: "***"

esp32dev_dallas_1wire_sensor: "0xAC000802CFE21XXX"
esp32dev_dallas_1wire_sensor: "0xAC00000000000000"

esp32dev_xiaomi_bt_1_mac_address: A4:C1:38:00:XX:YY ## Living room
esp32dev_xiaomi_bt_2_mac_address: A4:C1:38:00:XX:YY ## Kitchen
esp32dev_xiaomi_bt_3_mac_address: A4:C1:38:00:XX:YY ## Entry Hall
